### ISSUE TITLE
Create User Tab

### ISSUE THREAD

**Issue by sortedcord** [sortedcord/osu-statqt#33]
Make a Tab in MainWindow to display statistics of default user (Also display for user searched when #13 is worked on). 

Here is what the current layout looks like:

![image](https://user-images.githubusercontent.com/37407370/149062588-d94e11d8-6c52-4c08-826b-f4e5ec70ec1a.png)

## Todo

- [x] Create UI file and finish layout
- [x] Format Code in py files.
- [ ] Separate functions
- [ ] Setup Connections

## New Features

Features that you don't see on osu.ppy.sh-

- [ ] Total PP (Unweighted)
- [ ] Accuracy Pie Chart
- [ ] Most Played Mods
- [ ] First Place Ranks
